"""Larger universe for debasement-LEAPS scanning.

~300 US-listed names, all >$500M market cap at time of compilation,
organized by sector with per-name beta-to-M2 estimates. Used via:

    python3 scan_smooth.py --large

Betas are thematic anchors, not rigorous econometric estimates:
    1.0   gold, pure monetary hedge
    1.0-1.3   defensives, insurance, waste, telecom
    1.3-1.5   consumer compounders, toll-road financials, healthcare tools
    1.5-1.8   industrials, megacap tech, grid infra, defense
    1.8-2.2   semis, semi-cap, asset managers, storage
    2.3-3.0   photonics / AI networking, high-beta materials
    3.0+      crypto-beta equities, BTC proxies
"""

# (tv_symbol, beta_to_m2, theme)
LARGE_UNIVERSE: dict[str, tuple[str, float, str]] = {
    # ─── MEGACAP TECH ──────────────────────────────────────────────
    "AAPL": ("NASDAQ:AAPL",   1.7, "megacap"),
    "MSFT": ("NASDAQ:MSFT",   1.8, "megacap"),
    "GOOGL":("NASDAQ:GOOGL",  1.8, "megacap"),
    "META": ("NASDAQ:META",   2.0, "megacap"),
    "AMZN": ("NASDAQ:AMZN",   1.8, "megacap"),
    "ORCL": ("NYSE:ORCL",     1.8, "megacap"),
    "NVDA": ("NASDAQ:NVDA",   2.2, "semis"),
    "AVGO": ("NASDAQ:AVGO",   2.0, "semis"),
    "TSLA": ("NASDAQ:TSLA",   2.2, "auto_tech"),
    "NFLX": ("NASDAQ:NFLX",   1.8, "media_tech"),
    "ADBE": ("NASDAQ:ADBE",   1.8, "software"),
    "CRM":  ("NYSE:CRM",      1.8, "software"),
    "NOW":  ("NYSE:NOW",      1.8, "software"),
    "INTU": ("NASDAQ:INTU",   1.8, "software"),

    # ─── SOFTWARE ──────────────────────────────────────────────────
    "PANW": ("NASDAQ:PANW",   2.0, "software"),
    "CRWD": ("NASDAQ:CRWD",   2.0, "software"),
    "FTNT": ("NASDAQ:FTNT",   1.8, "software"),
    "ZS":   ("NASDAQ:ZS",     2.0, "software"),
    "NET":  ("NYSE:NET",      2.0, "software"),
    "DDOG": ("NASDAQ:DDOG",   2.0, "software"),
    "SNOW": ("NYSE:SNOW",     2.0, "software"),
    "PLTR": ("NASDAQ:PLTR",   2.5, "software"),
    "VEEV": ("NYSE:VEEV",     1.8, "software"),
    "WDAY": ("NASDAQ:WDAY",   1.8, "software"),
    "TEAM": ("NASDAQ:TEAM",   2.0, "software"),
    "HUBS": ("NYSE:HUBS",     2.0, "software"),
    "CDNS": ("NASDAQ:CDNS",   1.8, "eda"),
    "SNPS": ("NASDAQ:SNPS",   1.8, "eda"),
    "ADSK": ("NASDAQ:ADSK",   1.8, "eda"),
    "MNDY": ("NASDAQ:MNDY",   2.0, "software"),

    # ─── SEMIS / SEMI-CAP ─────────────────────────────────────────
    "AMD":  ("NASDAQ:AMD",    2.2, "semis"),
    "QCOM": ("NASDAQ:QCOM",   2.0, "semis"),
    "TXN":  ("NASDAQ:TXN",    1.8, "semis"),
    "MCHP": ("NASDAQ:MCHP",   2.0, "semis"),
    "ADI":  ("NASDAQ:ADI",    1.8, "semis"),
    "ON":   ("NASDAQ:ON",     2.0, "semis"),
    "NXPI": ("NASDAQ:NXPI",   1.8, "semis"),
    "AMAT": ("NASDAQ:AMAT",   2.0, "semi_cap"),
    "LRCX": ("NASDAQ:LRCX",   2.0, "semi_cap"),
    "KLAC": ("NASDAQ:KLAC",   2.0, "semi_cap"),
    "ASML": ("NASDAQ:ASML",   2.0, "semi_cap"),
    "TER":  ("NASDAQ:TER",    2.0, "semi_cap"),
    "ENTG": ("NASDAQ:ENTG",   2.0, "semi_cap"),
    "MKSI": ("NASDAQ:MKSI",   2.0, "semi_cap"),
    "ONTO": ("NYSE:ONTO",     2.2, "semi_cap"),
    "FORM": ("NASDAQ:FORM",   2.2, "semi_cap"),
    "ACLS": ("NASDAQ:ACLS",   2.2, "semi_cap"),
    "ICHR": ("NASDAQ:ICHR",   2.2, "semi_cap"),
    "UCTT": ("NASDAQ:UCTT",   2.2, "semi_cap"),
    "NVMI": ("NASDAQ:NVMI",   2.2, "semi_cap"),
    "COHU": ("NASDAQ:COHU",   2.2, "semi_cap"),
    "MRVL": ("NASDAQ:MRVL",   2.0, "semis"),
    "MPWR": ("NASDAQ:MPWR",   2.0, "semis"),
    "ALGM": ("NASDAQ:ALGM",   2.0, "semis"),
    "SWKS": ("NASDAQ:SWKS",   1.8, "semis"),
    "QRVO": ("NASDAQ:QRVO",   1.8, "semis"),
    "CRUS": ("NASDAQ:CRUS",   1.8, "semis"),
    "SITM": ("NASDAQ:SITM",   2.2, "semis"),
    "POWI": ("NASDAQ:POWI",   2.0, "semis"),
    "SLAB": ("NASDAQ:SLAB",   2.0, "semis"),
    "ALAB": ("NASDAQ:ALAB",   2.5, "ai_chip"),
    "CRDO": ("NASDAQ:CRDO",   2.5, "ai_network"),
    "MTSI": ("NASDAQ:MTSI",   2.2, "ai_network"),
    "GFS":  ("NASDAQ:GFS",    2.0, "semis"),
    # Storage / networking / optical
    "WDC":  ("NASDAQ:WDC",    2.0, "storage"),
    "STX":  ("NASDAQ:STX",    2.0, "storage"),
    "CIEN": ("NYSE:CIEN",     2.2, "optical"),
    "FN":   ("NYSE:FN",       2.5, "photonics"),
    "COHR": ("NASDAQ:COHR",   2.5, "photonics"),
    "LITE": ("NASDAQ:LITE",   2.5, "photonics"),
    "GLW":  ("NYSE:GLW",      1.8, "materials_tech"),
    "ANET": ("NYSE:ANET",     2.0, "networking"),
    "CSCO": ("NASDAQ:CSCO",   1.5, "networking"),

    # ─── MONEY CENTER / REGIONAL BANKS ─────────────────────────────
    "JPM":  ("NYSE:JPM",      1.2, "money_ctr_bank"),
    "BAC":  ("NYSE:BAC",      1.2, "money_ctr_bank"),
    "WFC":  ("NYSE:WFC",      1.2, "money_ctr_bank"),
    "C":    ("NYSE:C",        1.2, "money_ctr_bank"),
    "USB":  ("NYSE:USB",      1.2, "money_ctr_bank"),
    "PNC":  ("NYSE:PNC",      1.2, "money_ctr_bank"),
    "TFC":  ("NYSE:TFC",      1.2, "money_ctr_bank"),
    "GS":   ("NYSE:GS",       1.5, "ibank"),
    "MS":   ("NYSE:MS",       1.5, "ibank"),
    "AXP":  ("NYSE:AXP",      1.5, "payment_rail"),
    "V":    ("NYSE:V",        1.5, "payment_rail"),
    "MA":   ("NYSE:MA",       1.5, "payment_rail"),
    "FITB": ("NASDAQ:FITB",   1.2, "regional_bank"),
    "HBAN": ("NASDAQ:HBAN",   1.2, "regional_bank"),
    "KEY":  ("NYSE:KEY",      1.2, "regional_bank"),
    "RF":   ("NYSE:RF",       1.2, "regional_bank"),
    "CFG":  ("NYSE:CFG",      1.2, "regional_bank"),
    "MTB":  ("NYSE:MTB",      1.2, "regional_bank"),
    "WBS":  ("NYSE:WBS",      1.2, "regional_bank"),
    "ZION": ("NASDAQ:ZION",   1.2, "regional_bank"),
    "WAL":  ("NYSE:WAL",      1.2, "regional_bank"),
    "WTFC": ("NASDAQ:WTFC",   1.2, "regional_bank"),
    "PB":   ("NYSE:PB",       1.2, "regional_bank"),
    "BPOP": ("NASDAQ:BPOP",   1.2, "regional_bank"),

    # ─── INSURANCE ────────────────────────────────────────────────
    "BRK.B":("NYSE:BRK.B",    1.3, "conglomerate"),
    "PGR":  ("NYSE:PGR",      1.2, "insurance"),
    "TRV":  ("NYSE:TRV",      1.2, "insurance"),
    "ALL":  ("NYSE:ALL",      1.2, "insurance"),
    "CB":   ("NYSE:CB",       1.2, "insurance"),
    "HIG":  ("NYSE:HIG",      1.2, "insurance"),
    "AIG":  ("NYSE:AIG",      1.2, "insurance"),
    "WRB":  ("NYSE:WRB",      1.3, "insurance"),
    "ACGL": ("NASDAQ:ACGL",   1.3, "insurance"),
    "RNR":  ("NYSE:RNR",      1.3, "insurance"),
    "AJG":  ("NYSE:AJG",      1.3, "insurance_broker"),
    "BRO":  ("NYSE:BRO",      1.3, "insurance_broker"),
    "WTW":  ("NASDAQ:WTW",    1.3, "insurance_broker"),
    "AON":  ("NYSE:AON",      1.3, "insurance_broker"),
    "MET":  ("NYSE:MET",      1.2, "insurance"),
    "PRU":  ("NYSE:PRU",      1.2, "insurance"),

    # ─── ASSET MANAGERS ───────────────────────────────────────────
    "BLK":  ("NYSE:BLK",      2.0, "asset_mgr"),
    "KKR":  ("NYSE:KKR",      2.5, "alt_mgr"),
    "BX":   ("NYSE:BX",       2.5, "alt_mgr"),
    "APO":  ("NYSE:APO",      2.5, "alt_mgr"),
    "BAM":  ("NYSE:BAM",      2.0, "alt_mgr"),
    "BN":   ("NYSE:BN",       2.0, "alt_mgr"),
    "ARES": ("NYSE:ARES",     2.2, "alt_mgr"),
    "OWL":  ("NYSE:OWL",      2.2, "alt_mgr"),
    "CG":   ("NASDAQ:CG",     2.2, "alt_mgr"),
    "TROW": ("NASDAQ:TROW",   1.8, "asset_mgr"),
    "BEN":  ("NYSE:BEN",      1.8, "asset_mgr"),
    "LAZ":  ("NYSE:LAZ",      2.0, "ibank"),
    "SF":   ("NYSE:SF",       1.8, "ibank"),

    # ─── EXCHANGE / DATA / RATINGS ────────────────────────────────
    "SPGI": ("NYSE:SPGI",     1.5, "data_monopoly"),
    "MCO":  ("NYSE:MCO",      1.5, "data_monopoly"),
    "MSCI": ("NYSE:MSCI",     1.5, "data_monopoly"),
    "FICO": ("NYSE:FICO",     1.5, "data_monopoly"),
    "NDAQ": ("NASDAQ:NDAQ",   1.5, "exchange"),
    "ICE":  ("NYSE:ICE",      1.5, "exchange"),
    "CME":  ("NASDAQ:CME",    1.5, "exchange"),
    "CBOE": ("AMEX:CBOE",     1.5, "exchange"),

    # ─── CRYPTO-BETA / HIGH-BETA FINANCIALS ───────────────────────
    "HOOD": ("NASDAQ:HOOD",   3.0, "crypto_beta"),
    "COIN": ("NASDAQ:COIN",   3.5, "crypto_exch"),
    "MSTR": ("NASDAQ:MSTR",   4.0, "btc_proxy"),
    "SCHW": ("NYSE:SCHW",     1.5, "broker_dealer"),
    "IBKR": ("NASDAQ:IBKR",   1.5, "broker_dealer"),

    # ─── CONSUMER MOATS / COMPOUNDERS ─────────────────────────────
    "COST": ("NASDAQ:COST",   1.3, "consumer_moat"),
    "WMT":  ("NYSE:WMT",      1.2, "consumer_moat"),
    "HD":   ("NYSE:HD",       1.3, "consumer_moat"),
    "LOW":  ("NYSE:LOW",      1.3, "consumer_moat"),
    "TJX":  ("NYSE:TJX",      1.3, "consumer_moat"),
    "ROST": ("NASDAQ:ROST",   1.3, "consumer_moat"),
    "ORLY": ("NASDAQ:ORLY",   1.3, "consumer_moat"),
    "AZO":  ("NYSE:AZO",      1.3, "consumer_moat"),
    "ULTA": ("NASDAQ:ULTA",   1.3, "consumer_moat"),
    "MCD":  ("NYSE:MCD",      1.2, "consumer_moat"),
    "SBUX": ("NASDAQ:SBUX",   1.3, "consumer_moat"),
    "CMG":  ("NYSE:CMG",      1.5, "consumer_moat"),
    "YUM":  ("NYSE:YUM",      1.2, "consumer_moat"),
    "NKE":  ("NYSE:NKE",      1.3, "consumer_moat"),
    "PG":   ("NYSE:PG",       1.2, "consumer_staples"),
    "KO":   ("NYSE:KO",       1.2, "consumer_staples"),
    "PEP":  ("NASDAQ:PEP",    1.2, "consumer_staples"),
    "CL":   ("NYSE:CL",       1.2, "consumer_staples"),
    "KMB":  ("NYSE:KMB",      1.2, "consumer_staples"),
    "MDLZ": ("NASDAQ:MDLZ",   1.2, "consumer_staples"),
    "MNST": ("NASDAQ:MNST",   1.3, "consumer_staples"),
    "KDP":  ("NASDAQ:KDP",    1.2, "consumer_staples"),
    "PM":   ("NYSE:PM",       1.2, "consumer_staples"),
    "MO":   ("NYSE:MO",       1.0, "consumer_staples"),
    "BKNG": ("NASDAQ:BKNG",   1.5, "travel"),
    "ABNB": ("NASDAQ:ABNB",   1.5, "travel"),
    "MAR":  ("NASDAQ:MAR",    1.5, "hotels"),
    "HLT":  ("NYSE:HLT",      1.5, "hotels"),
    "WYNN": ("NASDAQ:WYNN",   1.8, "gaming"),
    "MGM":  ("NYSE:MGM",      1.8, "gaming"),
    "LVS":  ("NYSE:LVS",      1.8, "gaming"),
    "DKNG": ("NASDAQ:DKNG",   2.0, "gaming"),
    "CHDN": ("NASDAQ:CHDN",   1.5, "gaming"),

    # ─── INFRA SERVICE / COMPOUNDERS ──────────────────────────────
    "WM":   ("NYSE:WM",       1.2, "infra_service"),
    "RSG":  ("NYSE:RSG",      1.2, "infra_service"),
    "WCN":  ("NYSE:WCN",      1.2, "infra_service"),
    "CTAS": ("NASDAQ:CTAS",   1.3, "infra_service"),
    "ROL":  ("NYSE:ROL",      1.2, "infra_service"),
    "CPRT": ("NASDAQ:CPRT",   1.3, "auction_moat"),
    "PAYX": ("NASDAQ:PAYX",   1.3, "payroll"),
    "PAYC": ("NYSE:PAYC",     1.5, "payroll"),
    "ADP":  ("NASDAQ:ADP",    1.3, "payroll"),
    "VRSK": ("NASDAQ:VRSK",   1.3, "data_monopoly"),

    # ─── INDUSTRIAL COMPOUNDERS ───────────────────────────────────
    "GE":   ("NYSE:GE",       1.8, "industrial"),
    "HON":  ("NASDAQ:HON",    1.5, "industrial"),
    "MMM":  ("NYSE:MMM",      1.3, "industrial"),
    "ITW":  ("NYSE:ITW",      1.5, "industrial"),
    "ROP":  ("NASDAQ:ROP",    1.5, "industrial_sw"),
    "DHR":  ("NYSE:DHR",      1.5, "life_sci_tools"),
    "EMR":  ("NYSE:EMR",      1.5, "industrial"),
    "ROK":  ("NYSE:ROK",      1.8, "automation"),
    "ETN":  ("NYSE:ETN",      1.8, "electrification"),
    "PH":   ("NYSE:PH",       1.5, "industrial"),
    "APH":  ("NYSE:APH",      1.8, "connectors"),
    "TEL":  ("NYSE:TEL",      1.8, "connectors"),
    "HUBB": ("NYSE:HUBB",     1.8, "electrification"),
    "XYL":  ("NYSE:XYL",      1.5, "water_infra"),
    "AME":  ("NYSE:AME",      1.5, "industrial"),
    "FTV":  ("NYSE:FTV",      1.5, "industrial"),
    "DOV":  ("NYSE:DOV",      1.5, "industrial"),
    "IR":   ("NYSE:IR",       1.5, "industrial"),
    "PNR":  ("NYSE:PNR",      1.5, "water_infra"),
    "AOS":  ("NYSE:AOS",      1.3, "industrial"),
    "GNRC": ("NYSE:GNRC",     1.8, "industrial"),

    # ─── GRID / ELECTRIFICATION / CAPEX ───────────────────────────
    "PWR":  ("NYSE:PWR",      1.5, "grid_infra"),
    "GEV":  ("NYSE:GEV",      1.8, "grid_infra"),
    "MTZ":  ("NYSE:MTZ",      1.5, "grid_infra"),
    "FIX":  ("NYSE:FIX",      1.8, "hvac_datactr"),
    "IESC": ("NASDAQ:IESC",   1.8, "grid_infra"),
    "PRIM": ("NYSE:PRIM",     1.8, "grid_infra"),
    "MYRG": ("NASDAQ:MYRG",   1.8, "grid_infra"),
    "DY":   ("NYSE:DY",       1.5, "grid_infra"),
    "TT":   ("NYSE:TT",       1.5, "hvac_datactr"),
    "CARR": ("NYSE:CARR",     1.5, "hvac_datactr"),
    "JCI":  ("NYSE:JCI",      1.5, "hvac_datactr"),
    "LII":  ("NYSE:LII",      1.5, "hvac_datactr"),

    # ─── DEFENSE / AEROSPACE ──────────────────────────────────────
    "LMT":  ("NYSE:LMT",      1.3, "defense"),
    "NOC":  ("NYSE:NOC",      1.3, "defense"),
    "RTX":  ("NYSE:RTX",      1.3, "defense"),
    "GD":   ("NYSE:GD",       1.3, "defense"),
    "TDG":  ("NYSE:TDG",      1.5, "defense_aero"),
    "HEI":  ("NYSE:HEI",      1.5, "defense_aero"),
    "HWM":  ("NYSE:HWM",      1.5, "defense_aero"),
    "HXL":  ("NYSE:HXL",      1.5, "defense_aero"),
    "BA":   ("NYSE:BA",       1.3, "defense_aero"),
    "CW":   ("NYSE:CW",       1.5, "defense"),
    "HII":  ("NYSE:HII",      1.3, "defense"),
    "TXT":  ("NYSE:TXT",      1.3, "defense"),
    "KTOS": ("NASDAQ:KTOS",   2.0, "defense"),
    "AVAV": ("NASDAQ:AVAV",   2.0, "defense"),
    "LDOS": ("NYSE:LDOS",     1.3, "defense"),
    "BAH":  ("NYSE:BAH",      1.3, "defense"),
    "CACI": ("NYSE:CACI",     1.3, "defense"),

    # ─── TRANSPORTS ───────────────────────────────────────────────
    "UNP":  ("NYSE:UNP",      1.5, "rail"),
    "CSX":  ("NASDAQ:CSX",    1.5, "rail"),
    "NSC":  ("NYSE:NSC",      1.5, "rail"),
    "UPS":  ("NYSE:UPS",      1.3, "package"),
    "FDX":  ("NYSE:FDX",      1.3, "package"),
    "JBHT": ("NASDAQ:JBHT",   1.5, "trucking"),
    "ODFL": ("NASDAQ:ODFL",   1.5, "trucking"),
    "XPO":  ("NYSE:XPO",      1.5, "trucking"),
    "SAIA": ("NASDAQ:SAIA",   1.5, "trucking"),
    "KNX":  ("NYSE:KNX",      1.5, "trucking"),
    "LSTR": ("NASDAQ:LSTR",   1.5, "trucking"),
    "MATX": ("NYSE:MATX",     1.5, "shipping"),
    "DAL":  ("NYSE:DAL",      1.8, "airline"),
    "UAL":  ("NASDAQ:UAL",    1.8, "airline"),
    "LUV":  ("NYSE:LUV",      1.5, "airline"),

    # ─── HEALTHCARE ───────────────────────────────────────────────
    "LLY":  ("NYSE:LLY",      1.5, "pharma_glp1"),
    "JNJ":  ("NYSE:JNJ",      1.2, "pharma"),
    "ABBV": ("NYSE:ABBV",     1.3, "pharma"),
    "MRK":  ("NYSE:MRK",      1.3, "pharma"),
    "PFE":  ("NYSE:PFE",      1.2, "pharma"),
    "BMY":  ("NYSE:BMY",      1.2, "pharma"),
    "VRTX": ("NASDAQ:VRTX",   1.5, "biotech_monopoly"),
    "REGN": ("NASDAQ:REGN",   1.5, "biotech"),
    "AMGN": ("NASDAQ:AMGN",   1.3, "biotech"),
    "GILD": ("NASDAQ:GILD",   1.3, "biotech"),
    "UNH":  ("NYSE:UNH",      1.3, "managed_care"),
    "ELV":  ("NYSE:ELV",      1.3, "managed_care"),
    "CI":   ("NYSE:CI",       1.3, "managed_care"),
    "HUM":  ("NYSE:HUM",      1.3, "managed_care"),
    "ISRG": ("NASDAQ:ISRG",   1.8, "med_device"),
    "BSX":  ("NYSE:BSX",      1.5, "med_device"),
    "SYK":  ("NYSE:SYK",      1.5, "med_device"),
    "MDT":  ("NYSE:MDT",      1.3, "med_device"),
    "EW":   ("NYSE:EW",       1.5, "med_device"),
    "BDX":  ("NYSE:BDX",      1.3, "med_device"),
    "PODD": ("NASDAQ:PODD",   1.8, "med_device"),
    "DXCM": ("NASDAQ:DXCM",   1.8, "med_device"),
    "ABT":  ("NYSE:ABT",      1.3, "med_device"),
    "TMO":  ("NYSE:TMO",      1.5, "life_sci_tools"),
    "A":    ("NYSE:A",        1.5, "life_sci_tools"),
    "WAT":  ("NYSE:WAT",      1.5, "life_sci_tools"),
    "IQV":  ("NYSE:IQV",      1.5, "life_sci_tools"),
    "MTD":  ("NYSE:MTD",      1.5, "life_sci_tools"),
    "ZTS":  ("NYSE:ZTS",      1.3, "vet"),
    "IDXX": ("NASDAQ:IDXX",   1.3, "vet_diagnostics"),

    # ─── REAL ESTATE (selective) ──────────────────────────────────
    "EQIX": ("NASDAQ:EQIX",   1.8, "data_center_reit"),
    "DLR":  ("NYSE:DLR",      1.8, "data_center_reit"),
    "AMT":  ("NYSE:AMT",      1.3, "tower_reit"),
    "CCI":  ("NYSE:CCI",      1.3, "tower_reit"),
    "PSA":  ("NYSE:PSA",      1.2, "storage_reit"),
    "EXR":  ("NYSE:EXR",      1.2, "storage_reit"),
    "PLD":  ("NYSE:PLD",      1.3, "industrial_reit"),
    "WELL": ("NYSE:WELL",     1.3, "health_reit"),
    "VICI": ("NYSE:VICI",     1.3, "gaming_reit"),
    "IRM":  ("NYSE:IRM",      1.3, "specialty_reit"),

    # ─── ENERGY / E&P / SERVICES ──────────────────────────────────
    "XOM":  ("NYSE:XOM",      1.5, "integrated_oil"),
    "CVX":  ("NYSE:CVX",      1.5, "integrated_oil"),
    "COP":  ("NYSE:COP",      1.8, "ep"),
    "EOG":  ("NYSE:EOG",      1.8, "ep"),
    "HES":  ("NYSE:HES",      1.8, "ep"),
    "OXY":  ("NYSE:OXY",      1.8, "ep"),
    "FANG": ("NASDAQ:FANG",   1.8, "ep"),
    "CTRA": ("NYSE:CTRA",     1.8, "ep"),
    "MPC":  ("NYSE:MPC",      1.5, "refiner"),
    "VLO":  ("NYSE:VLO",      1.5, "refiner"),
    "PSX":  ("NYSE:PSX",      1.5, "refiner"),
    "SLB":  ("NYSE:SLB",      1.8, "energy_svc"),
    "HAL":  ("NYSE:HAL",      1.8, "energy_svc"),
    "BKR":  ("NASDAQ:BKR",    1.8, "energy_svc"),
    "FTI":  ("NYSE:FTI",      1.8, "energy_svc"),
    "NOV":  ("NYSE:NOV",      1.8, "energy_svc"),
    "WMB":  ("NYSE:WMB",      1.3, "midstream"),
    "KMI":  ("NYSE:KMI",      1.3, "midstream"),
    "OKE":  ("NYSE:OKE",      1.3, "midstream"),
    "ENB":  ("NYSE:ENB",      1.3, "midstream"),
    "LNG":  ("AMEX:LNG",      1.8, "lng"),
    "CEG":  ("NASDAQ:CEG",    1.8, "nuclear_util"),
    "VST":  ("NYSE:VST",      1.8, "nuclear_util"),
    "NRG":  ("NYSE:NRG",      1.5, "power_util"),

    # ─── MATERIALS / COMMODITIES ──────────────────────────────────
    "LIN":  ("NASDAQ:LIN",    1.3, "industrial_gas"),
    "APD":  ("NYSE:APD",      1.3, "industrial_gas"),
    "SHW":  ("NYSE:SHW",      1.3, "chemicals"),
    "ECL":  ("NYSE:ECL",      1.3, "chemicals"),
    "PPG":  ("NYSE:PPG",      1.3, "chemicals"),
    "DD":   ("NYSE:DD",       1.3, "chemicals"),
    "LYB":  ("NYSE:LYB",      1.5, "chemicals"),
    "MOS":  ("NYSE:MOS",      1.8, "fertilizer"),
    "CF":   ("NYSE:CF",       1.8, "fertilizer"),
    "NTR":  ("NYSE:NTR",      1.8, "fertilizer"),
    "FCX":  ("NYSE:FCX",      2.0, "copper"),
    "SCCO": ("NYSE:SCCO",     2.0, "copper"),
    "NUE":  ("NYSE:NUE",      1.8, "steel"),
    "STLD": ("NASDAQ:STLD",   1.8, "steel"),
    "CLF":  ("NYSE:CLF",      2.0, "steel"),
    "NEM":  ("NYSE:NEM",      2.0, "gold"),
    "AEM":  ("NYSE:AEM",      2.0, "gold"),
    "GOLD": ("NYSE:GOLD",     2.0, "gold"),
    "FNV":  ("NYSE:FNV",      1.8, "gold_royalty"),
    "WPM":  ("NYSE:WPM",      2.0, "silver_royalty"),
    "KGC":  ("NYSE:KGC",      2.2, "gold"),
    "AG":   ("NYSE:AG",       2.2, "silver"),
    "PAAS": ("NASDAQ:PAAS",   2.2, "silver"),
    "SSRM": ("NASDAQ:SSRM",   2.2, "silver"),
    "HL":   ("NYSE:HL",       2.2, "silver"),
    "EGO":  ("NYSE:EGO",      2.2, "gold"),
    "IAG":  ("NYSE:IAG",      2.2, "gold"),
    "CCJ":  ("NYSE:CCJ",      2.2, "uranium"),
    "LEU":  ("AMEX:LEU",      2.5, "uranium"),
    "UEC":  ("AMEX:UEC",      2.5, "uranium"),
    "DNN":  ("AMEX:DNN",      2.5, "uranium"),
    "UUUU": ("AMEX:UUUU",     2.5, "uranium"),
    "BWXT": ("NYSE:BWXT",     1.5, "nuclear"),
    "VMC":  ("NYSE:VMC",      1.5, "building_materials"),
    "MLM":  ("NYSE:MLM",      1.5, "building_materials"),
    "EXP":  ("NYSE:EXP",      1.5, "building_materials"),

    # ─── HOMEBUILDERS / BUILDING PRODUCTS ────────────────────────
    "DHI":  ("NYSE:DHI",      1.5, "homebuilder"),
    "LEN":  ("NYSE:LEN",      1.5, "homebuilder"),
    "PHM":  ("NYSE:PHM",      1.5, "homebuilder"),
    "NVR":  ("NYSE:NVR",      1.5, "homebuilder"),
    "TOL":  ("NYSE:TOL",      1.5, "homebuilder"),
    "MTH":  ("NYSE:MTH",      1.5, "homebuilder"),
    "TPH":  ("NYSE:TPH",      1.5, "homebuilder"),
    "MHO":  ("NYSE:MHO",      1.5, "homebuilder"),
    "BLDR": ("NYSE:BLDR",     1.8, "building_prod"),
    "IBP":  ("NYSE:IBP",      1.8, "building_prod"),

    # ─── TELECOM / MEDIA ──────────────────────────────────────────
    "TMUS": ("NASDAQ:TMUS",   1.3, "telecom"),
    "T":    ("NYSE:T",        1.0, "telecom"),
    "VZ":   ("NYSE:VZ",       1.0, "telecom"),
    "DIS":  ("NYSE:DIS",      1.3, "media"),

    # ─── AGRI / FOOD ──────────────────────────────────────────────
    "DE":   ("NYSE:DE",       1.5, "ag_equip"),
    "AGCO": ("NYSE:AGCO",     1.5, "ag_equip"),
    "CTVA": ("NYSE:CTVA",     1.5, "ag"),
    "TSN":  ("NYSE:TSN",      1.2, "food"),
    "HSY":  ("NYSE:HSY",      1.2, "food"),
    "GIS":  ("NYSE:GIS",      1.2, "food"),

    # ─── ENGINEERING & CONSTRUCTION ───────────────────────────────
    "ACM":  ("NYSE:ACM",      1.5, "ec"),
    "J":    ("NYSE:J",        1.5, "ec"),
    "FLR":  ("NYSE:FLR",      1.8, "ec"),
    "KBR":  ("NYSE:KBR",      1.5, "ec"),
    "EME":  ("NYSE:EME",      1.8, "electrical_svc"),
    "TTEK": ("NASDAQ:TTEK",   1.5, "env_eng"),
    "STRL": ("NASDAQ:STRL",   1.8, "ec"),
    "JBL":  ("NYSE:JBL",      2.0, "contract_mfg"),
    "FLEX": ("NASDAQ:FLEX",   1.8, "contract_mfg"),
    "KEYS": ("NYSE:KEYS",     1.8, "test_mmt"),
    "A":    ("NYSE:A",        1.5, "test_mmt"),

    # ─── LIFESTYLE / OTHER ────────────────────────────────────────
    "LIT":  ("AMEX:LIT",      2.0, "battery_etf"),
    "GDX":  ("AMEX:GDX",      2.0, "gold_miners_etf"),
    "GDXJ": ("AMEX:GDXJ",     2.2, "gold_miners_etf"),
    "URA":  ("AMEX:URA",      2.5, "uranium_etf"),
    "URNM": ("AMEX:URNM",     2.5, "uranium_etf"),
    "SMH":  ("AMEX:SMH",      2.0, "semis_etf"),
    "SOXX": ("NASDAQ:SOXX",   2.0, "semis_etf"),
    "COPX": ("AMEX:COPX",     2.0, "copper_etf"),
    "XME":  ("AMEX:XME",      2.0, "metals_etf"),
    "XOP":  ("AMEX:XOP",      1.8, "oil_etf"),
    "XLE":  ("AMEX:XLE",      1.5, "energy_etf"),
    "IBIT": ("NASDAQ:IBIT",   4.0, "btc_etf"),
}
